set(CMAKE_SYSTEM_NAME Linux CACHE STRING "" FORCE)

if(DEFINED ENV{TRACKER_C_COMPILER_BIN} AND
   NOT "$ENV{TRACKER_C_COMPILER_BIN}" STREQUAL "")
    set(CMAKE_C_COMPILER "$ENV{TRACKER_C_COMPILER_BIN}" CACHE FILEPATH "" FORCE)
else()
    find_program(_tracker_gcc_c NAMES gcc cc REQUIRED)
    set(CMAKE_C_COMPILER "${_tracker_gcc_c}" CACHE FILEPATH "" FORCE)
endif()

if(DEFINED ENV{TRACKER_CXX_COMPILER_BIN} AND
   NOT "$ENV{TRACKER_CXX_COMPILER_BIN}" STREQUAL "")
    set(CMAKE_CXX_COMPILER "$ENV{TRACKER_CXX_COMPILER_BIN}" CACHE FILEPATH "" FORCE)
else()
    find_program(_tracker_gcc_cxx NAMES g++ c++ REQUIRED)
    set(CMAKE_CXX_COMPILER "${_tracker_gcc_cxx}" CACHE FILEPATH "" FORCE)
endif()

set(TRACKER_BUILD_PROFILE "high_assurance" CACHE STRING "" FORCE)
set(TRACKER_OPEN_SOURCE_TOOLCHAIN ON CACHE BOOL "" FORCE)

message(STATUS "Using open-source GCC toolchain: ${CMAKE_C_COMPILER} / ${CMAKE_CXX_COMPILER}")
