set(CMAKE_SYSTEM_NAME Linux CACHE STRING "" FORCE)

if(DEFINED ENV{TRACKER_C_COMPILER_BIN} AND
   NOT "$ENV{TRACKER_C_COMPILER_BIN}" STREQUAL "")
    set(CMAKE_C_COMPILER "$ENV{TRACKER_C_COMPILER_BIN}" CACHE FILEPATH "" FORCE)
else()
    find_program(_tracker_clang_c NAMES clang REQUIRED)
    set(CMAKE_C_COMPILER "${_tracker_clang_c}" CACHE FILEPATH "" FORCE)
endif()

if(DEFINED ENV{TRACKER_CXX_COMPILER_BIN} AND
   NOT "$ENV{TRACKER_CXX_COMPILER_BIN}" STREQUAL "")
    set(CMAKE_CXX_COMPILER "$ENV{TRACKER_CXX_COMPILER_BIN}" CACHE FILEPATH "" FORCE)
else()
    find_program(_tracker_clang_cxx NAMES clang++ REQUIRED)
    set(CMAKE_CXX_COMPILER "${_tracker_clang_cxx}" CACHE FILEPATH "" FORCE)
endif()

set(TRACKER_BUILD_PROFILE "high_assurance" CACHE STRING "" FORCE)
set(TRACKER_OPEN_SOURCE_TOOLCHAIN ON CACHE BOOL "" FORCE)

message(STATUS "Using open-source Clang toolchain: ${CMAKE_C_COMPILER} / ${CMAKE_CXX_COMPILER}")
